### ISSUE TITLE
Problem when open TIFF images

### ISSUE THREAD

**Issue by cassiabmac** [johnkoestel/soilj#1]
I selected the folder, but I get this error: 

(Fiji Is Just) ImageJ 2.0.0-rc-71/1.52p; Java 1.8.0_211 [64-bit]; Windows 10 10.0; 81MB of 12125MB (<1%)
 
java.lang.IllegalArgumentException: Stack is empty
	at ij.ImagePlus.setStack(ImagePlus.java:686)
	at ij.ImagePlus.setStack(ImagePlus.java:675)
	at SoilJ.tools.InputOutput.openTiff3DSomeSlices(InputOutput.java:850)
	at SoilJ_.PoreSpaceAnalyzer_.run(PoreSpaceAnalyzer_.java:164)
	at ij.IJ.runUserPlugIn(IJ.java:230)
	at ij.IJ.runPlugIn(IJ.java:193)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Unknown Source)

**Comment by johnkoestel** [comment]
Hej cassiabmac, 
I will upload a new SoilJ version that makes opening files easier. 
In the new version, you select a TIFF file directly and then are given the choice to only process the 
selected TIFF or all Tiff in the respective folder.
Cheers, 
/John

**Comment by cassiabmac** [comment]
I selected to open the entire stack, but the same thing happened. 

`(Fiji Is Just) ImageJ 2.0.0-rc-69/1.52p; Java 1.8.0_172 [64-bit]; Windows 10 10.0; 99MB of 12125MB (<1%)
 
java.lang.IllegalArgumentException: Stack is empty
	at ij.ImagePlus.setStack(ImagePlus.java:686)
	at ij.ImagePlus.setStack(ImagePlus.java:675)
	at SoilJ.tools.InputOutput.openTiff3DSomeSlices(InputOutput.java:1074)
	at SoilJ_.PoreSpaceAnalyzer_.run(PoreSpaceAnalyzer_.java:85)
	at ij.IJ.runUserPlugIn(IJ.java:230)
	at ij.IJ.runPlugIn(IJ.java:193)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by johnkoestel** [comment]
Did you already download the latest SoilJ version (1.2.0) into your ImageJ plugin folder? 
(also make sure that you delete all old soilJ versions and restart ImageJ). 

If you have done all this, it should be either related to your image or to your choice of ROI. 
Note that the PoreSpaceAnalyzer needs a 8-bit image to work.

**Comment by ShengpingLi** [comment]
Dear Prof. John Koestel,
My ROI is cubiod, so I need to check "Cubiod ROI".  How to import the paraments in the following link? If I choose the whole ROI, can I import zero for every parament, for example the value of "Left X-coordinate of cubiod" is zero. Because I see the explanation (0 corresponds to maximum) in the window.
  @@![image](https://user-images.githubusercontent.com/56432905/66639867-0b08b100-ec18-11e9-8854-226ba88fac6d.png)
The second question is that I did use 8-bit image for PoreSpaceAnalyzer, but it cannot work. The following window appears.
 (Fiji Is Just) ImageJ 2.0.0-rc-69/1.52p; Java 1.8.0_172 [64-bit]; Windows 10 10.0; 796MB of 12135MB (6%)
 
java.lang.NoClassDefFoundError: org/doube/bonej/Connectivity
	at SoilJ.copiedTools.JParticleCounter.getEulerCharacter(JParticleCounter.java:293)
	at SoilJ.tools.MorphologyAnalyzer.parallelParticleAnalyzer(MorphologyAnalyzer.java:1275)
	at SoilJ.tools.MorphologyAnalyzer.tailoredPoreSpaceAnalyzer(MorphologyAnalyzer.java:2516)
	at SoilJ_.PoreSpaceAnalyzer_.run(PoreSpaceAnalyzer_.java:93)
	at ij.IJ.runUserPlugIn(IJ.java:230)
	at ij.IJ.runPlugIn(IJ.java:193)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:748)

Best regards,
Shengping Li

**Comment by johnkoestel** [comment]
Hej Shengping Li, 
it seems that the error is due to a missing plugin that SoilJ is still dependent on. Please download the updated manual (version 0.5) and follow the soilJ installation steps described therein. I also recommend you to use the latest SoilJ version (1.2.1), which is now uploaded to the github repository. 
Best regards and thanks you for informing me of the problem.
/John
