### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by vinxenz** [johnkoestel/soilj#2]
Hi john,
i have installed this plugin in fijij. I have tested the FindColumnOutlines feature on the newer version and after the elaboration I get an empty InnerCircle folder. Then I have tested the same in the older version an I get this error:
(Fiji Is Just) ImageJ 2.0.0-rc-69/1.52p; Java 1.8.0_172 [64-bit]; Windows 7 6.1; 451MB of 6104MB (7%)
 
java.lang.ArrayIndexOutOfBoundsException: 60
	at SoilJ.tools.InputOutput.assembleRepresentativeSample(InputOutput.java:327)
	at SoilJ_.FindColumnOutlines_.run(FindColumnOutlines_.java:156)
	at ij.IJ.runUserPlugIn(IJ.java:230)
	at ij.IJ.runPlugIn(IJ.java:193)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:748)

I need to extract more layers from ct images.

**Comment by johnkoestel** [comment]
Hej hej,
Better use the newest version.
Have you visualized the column finding?
In any event, I am on holidays right now and will have a closer look at your case on Monday.
Cheers,
John
________________________________________

**Comment by vinxenz** [comment]
No, In the newest version I get empty result.

**Comment by johnkoestel** [comment]
Hej Vinxenz,

Could you send me a link to one of your images, so that I could get a better idea of what the problem is?

Cheers,

/John

**Comment by vinxenz** [comment]
![BRUNO^MARIA_ROSARIA_000](https://user-images.githubusercontent.com/7724523/69537230-fb52eb00-0f7f-11ea-931f-3b3dfc5dc801.JPG)
![BRUNO^MARIA_ROSARIA_002](https://user-images.githubusercontent.com/7724523/69537236-fe4ddb80-0f7f-11ea-9429-b7bc25a257bd.JPG)

**Comment by johnkoestel** [comment]
Dear Vinxenz,
You want to analyze radiographs of teeth?!?
No wonder that soilJ did not work. It is neither designed to analyze radiographs nor to analyze teeth.
Please try with a different approach.
Good luck and best regards,
/John

**Comment by vinxenz** [comment]
HI John,
can you post me images that works ? Which type of images are correct?

**Comment by johnkoestel** [comment]
3-D images of soils or other geomaterials.
